[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
        'forge-std/=lib/forge-std/src/', 
        '@openzeppelin/=lib/openzeppelin-contracts/', 
        '@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/',
        'ds-test/=lib/forge-std/lib/ds-test/src/',
        'erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/',
        'forge-gas-snapshot/=lib/permit2/lib/forge-gas-snapshot/src/',
        'permit2/=lib/permit2/',
        'solmate/=lib/solmate/src/'
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
